swagger: "2.0"
info:
  title: "Cosmonet API's"
  description: "Swagger documentaion for the api's "
  version: 1.0

tags:
  - name: "Auth"
    description: "Where users logs in"

    # servers :
    #   -url : "http://localhost:3000"
    #   description: this is the local server
    #   -url : "http://localhost:4000"
    #   description: this is the front end server / production server

schemas:
  - "http"
  - "https"

paths:
  /api/signup:
    post:
      tags:
        - "Auth"
      summary: "use this to signup the new user"
      description: ""
      consumes:
        - "application/json"
        - "application/xml"
      parameters:
        - in: "body"
          name: "body"
          description: "user object"
          required: true
          schema:
            $ref: "#/definitions/userSignup"
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: Error
        "500":
          description: Internal Server Error
  /api/login:
    post:
      tags:
        - "Auth"
      summary: "login api"
      description: "use the email and password to login "
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "user login object"
          schema:
            $ref: "#/definitions/userLogin"
      responses:
        "200":
          description: "Logged in Successfully"
        "400":
          description: "Error"
        "500":
          description: "Internal server error"

  /api/forgotPassword:
    post:
      tags:
        - "Auth"
      summary: "Forgot password api"
      description: "Enter your registered email to get the password reset link"
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "forgot password object"
          schema:
            $ref: "#/definitions/userForgotPassword"
      responses:
        "200":
          description: "Forgot password link sent to entered email"
        "404":
          description: "user not found"
        "500":
          description: "Internal server error"
# securityDefinitions:
definitions:
  userSignup:
    type: "object"
    properties:
      fullName:
        type: "string"
      email:
        type: "string"
      phoneNumber:
        type: "integer"
      password:
        type: "string"
    xml:
      name: "userSignup"

  userLogin:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
    xml:
      name: "userLogin"

  userForgotPassword:
    type: "object"
    properties:
      email:
        type: "string"
    xml:
      name: "userForgotPassword"
